### ISSUE TITLE
Etzel joining in the wrong class

### ISSUE THREAD

**Issue by kekosaurus-rex** [eLTehh/Raddomizer#11]
![etzels](https://user-images.githubusercontent.com/113814014/190884626-3b8debba-7615-4d66-a4a2-49301d817c54.JPG)
![what exactly is this](https://user-images.githubusercontent.com/113814014/190884631-1358f658-901a-4150-bd79-16a974ad15af.JPG)
![current](https://user-images.githubusercontent.com/113814014/190884991-1032784e-0a7a-41c8-a169-583920af8a41.jpg) (Dsv doesnt work on github.)

[randomizerLog1238962580.txt](https://github.com/eLTehh/Raddomizer/files/9593007/randomizerLog1238962580.txt)
For some reason etzel joined in his base class instead of manakete. This was on maniac difficulty, and on 0.9.7, With the prologue choices gordin->ogma->cain and with every gaiden done, if any of these things are relevant.

Note: While not as important, Ellerean did the same thing in the next chapter, starting as a mage instead of cavalier, but caesar and radd didn't.

**Comment by eLTehh** [comment]
Should be fixed in the new update. Thanks for reporting!
