### ISSUE TITLE
Randomizer stuck on randomizing characters 1/77

### ISSUE THREAD

**Issue by Kinetic1000** [eLTehh/Raddomizer#2]
It's been stuck for the last 10 minutes. The error.log file is completely empty.
![image](https://user-images.githubusercontent.com/77944216/180624909-b506cc1e-4baf-48ee-96f7-a4eb64d16bd3.png)
0.9.4

**Comment by Kinetic1000** [comment]
Some further testing:

- Works fine with only growths or bases selected
- Errors with classes selected
2022-07-23 16:27:31,349 ERROR fe12dataReader Exception on randomizer
Traceback (most recent call last):
  File "fe12dataReader.py", line 173, in randomize
  File "fe12dataReader.py", line 541, in randomizeGameData
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:/Roms/DS/New Mystery of the Emblem/release/dslazy/NDS_UNPACK\\data\\data\\FE12data.bin.decmp'

**Comment by eLTehh** [comment]
Hmm, that's strange. ".decmp" file is the temporary file created that the randomizer pulls from FE12. Are you running multiple instances of the randomizer at the same time?

Try opening Task Manager and killing all instances of Raddomizer. I think it would also be preferable to (freshly) unpack your ROM again

I'll look into the results generated by your seed for the time being. Hang in there!

**Comment by eLTehh** [comment]
Okay, from what I can deduce it seems like an error with the growths range. Let me look into it and I'll push out a new update that can work with it.

**Comment by Kinetic1000** [comment]
Alright idk if this helps but more testing with seed 134668836
- With bases and classes on, it will work
- If I toggle on growths with those, it gets stuck on 2/77
![image](https://user-images.githubusercontent.com/77944216/180626505-c06b28fe-e5e9-40e5-973f-3d2592da38e2.png)

**Comment by eLTehh** [comment]
Pushed out a new update. Please try using this!

Also open Task Manager and kill all instances of the randomizer, just in case.

https://github.com/eLTehh/Raddomizer/releases/tag/v0.9.5

**Comment by Kinetic1000** [comment]
it worked, thanks
![image](https://user-images.githubusercontent.com/77944216/180626957-da6c10e8-7ae1-4c79-8483-340f93794788.png)

**Comment by eLTehh** [comment]
Great to hear! Thanks for the report :D
