### ISSUE TITLE
Caeda/Wrys replacements have wrong classes if you pick Athena P-4

### ISSUE THREAD

**Issue by Kinetic1000** [eLTehh/Raddomizer#4]
If you choose Athena's map during the prologue, then the replacements for Caeda and Wrys will always have their classes instead of what they are supposed to be randomized to. According to someone on discord, they will have the correct classes if you pick Jeorge's map.
(They also said that Matthis in C3 is always a cav instead of what he's supposed to be but I haven't gotten there yet)
[randomizerLog842238993.txt](https://github.com/eLTehh/Raddomizer/files/9174938/randomizerLog842238993.txt)
![image](https://user-images.githubusercontent.com/77944216/180628473-02a0d92e-eece-48e7-9b03-0f60a08231a7.png)

**Comment by eLTehh** [comment]
Iiinteresting, I think the dispos might not have the right pointers? Send your save file (before the chapter) and I'll take a look

**Comment by eLTehh** [comment]
Also randomizerlog too, so I can replicate it

**Comment by Kinetic1000** [comment]
I already sent my log in the first post, here's my save (github can't upload the save file directly)
[New Mystery of the Emblem-randomized.zip](https://github.com/eLTehh/Raddomizer/files/9174957/New.Mystery.of.the.Emblem-randomized.zip)

**Comment by eLTehh** [comment]
Whoops, sorry, missed the log

Anyway,  I think I found the issue regarding Matthis, looks like he has two pointers on the same map. Will have to hunt for the other two prologue pointers later.

For now try replacing disposPointers.json with the following file (please unzip ofc), re randomize with the same seed/settings and check if Matthis is fixed
[disposPointers.zip](https://github.com/eLTehh/Raddomizer/files/9174958/disposPointers.zip)

**Comment by Kinetic1000** [comment]
I'll test it when I get there since I don't have the save

**Comment by eLTehh** [comment]
Adding a note that C5 Rickard also appears to be default class, will look into it

**Comment by eLTehh** [comment]
Fixed with the new update. If more characters are found, do report the issue!
https://github.com/eLTehh/Raddomizer/releases/tag/v0.9.6
