### ISSUE TITLE
Wendell replacement is not promoted

### ISSUE THREAD

**Issue by Kinetic1000** [eLTehh/Raddomizer#7]
Wendell is a sage in the vanilla game, however his replacement was a mage for me.
![image](https://user-images.githubusercontent.com/77944216/180893232-39026adc-0a69-4891-8094-b910f27522fd.png)

**Comment by eLTehh** [comment]
Fixed for v0.9.7. Thanks for the report, as always!
https://github.com/eLTehh/Raddomizer/releases/tag/v0.9.7

(I should probably put your name in the credits at this point)
